check config and env

diff --git a/run/entrypoint-geth b/run/entrypoint-geth
--- a/run/entrypoint-geth
+++ b/run/entrypoint-geth
@@ -1,6 +1,21 @@
 #!/bin/bash
 set -eu
 
+# Check environment variables
+reqenv() {
+    if [ -z "${!1:-}" ]; then
+        echo "Error: environment variable '$1' is not set. check .env file!"
+        exit 1
+    fi
+}
+reqenv "CONFIG_DIR"
+reqenv "L1_RPC_URL"
+reqenv "L1_BEACON_URL"
+reqenv "L1_CHAIN_ID"
+reqenv "L2_CHAIN_ID"
+reqenv "FAUCET_PRIVATE_KEY"
+reqenv "FAUCET_ADDRESS"
+
 SEQUENCER_MODE=${SEQUENCER_MODE:-false}
 ADDITIONAL_ARGS=""
 
